[build]
  functions = "netlify/functions"
  publish = "."

[functions]
  node_bundler = "esbuild"

[build.environment]
  GITHUB_TOKEN = "placeholder"
  GITHUB_OWNER = "placeholder"
  GITHUB_REPO = "placeholder"
  ADMIN_PASSWORD = "placeholder"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.processing]

  [build.processing.css]

  [build.processing.html]

  [build.processing.images]

  [build.processing.js]

[build.services]